#--------------------------- 推广客设置 --------------------------start

taobao:
  is_open: False
  app_key: ''
  app_secret: ''
  adzone_id: ''
  group_material_id: '3756,28026,27446,13366,3786,3767,27448,13367,3788'
  
jingdong:
  is_open: True
  app_key: ''
  app_secret: ''
  site_id: ''
  suo_im: ''
  group_material_id: '10'
  
pinduoduo:
  is_open: False
  app_key: ''
  app_secret: ''
  p_id: ''
  group_material_id: '1,2'
  
suning:
  is_open: False
  app_key: ''
  app_secret: ''
  ad_book_id: ''
  group_material_id: '2179'
#--------------------------- 推广客设置  --------------------------end

#---------图片配置----start
image:
  download_path: E:\images\
#---------图片配置----end